version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=SistemaIndicadoresDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - sistema-indicadores-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - sistema-indicadores-network

networks:
  sistema-indicadores-network:
    driver: bridge

volumes:
  sqldata: 